apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
    - name: helloworld
      image: irynalian/kubernetes
      ports:
        - name: nodejs-port
          containerPort: 3000
